# Base image for Python environment
FROM python:3.11

WORKDIR /app
COPY backend/requirements.txt .
RUN pip install -r requirements.txt
COPY backend .
EXPOSE 8000
CMD ["gunicorn","--bind","0.0.0.0:8000","--worker-class","uvicorn.workers.UvicornWorker" ,"app:app"]